// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IEntypo:login': typeof import('~icons/entypo/login')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IHumbleicons:logout': typeof import('~icons/humbleicons/logout')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'ITwemoji:ninjaMediumLightSkinTone': typeof import('~icons/twemoji/ninja-medium-light-skin-tone')['default']
    LoginForm: typeof import('./src/components/account/LoginForm.vue')['default']
    RegistrationForm: typeof import('./src/components/account/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
