from main.api import api


def test_api_json_openapi(client, administrator):
    """Test endpoint which provide autogenerated openapi.json"""
    client.force_login(administrator)
    response = client.get(f"{api.root_path}{api.openapi_url[1:]}")
    assert response.status_code == 200
    assert response.json()["info"]["title"] == "NinjaAPI"


def test_api_docs(client, administrator):
    """Test the /api/docs endpoint"""
    client.force_login(administrator)
    response = client.get(f"{api.root_path}docs")
    assert response.status_code == 200


def test_visitor_cannot_access_api(client, visitor):
    """Test that visitor cannot access API"""
    client.force_login(visitor)
    response = client.get(f"{api.root_path}docs")
    assert response.status_code == 302
    assert response.url == "/admin/login/?next=/api/docs"
